
-- ARTICLE TYPES TABLE
CREATE TABLE IF NOT EXISTS article_types (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description TEXT
);

-- ARTICLES TABLE
CREATE TABLE IF NOT EXISTS articles (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    image_link VARCHAR(500),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    text LONGTEXT,
    view_count INT UNSIGNED DEFAULT 0,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- RELATIONS TABLE
CREATE TABLE IF NOT EXISTS relations (
    article_id INT UNSIGNED,
    article_type_id INT UNSIGNED
);